const DimmedGraph = ({ className }) => (
  <svg
    className={className}
    width="460"
    height="173"
    viewBox="0 0 460 173"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      y="65"
      width="12"
      height="108"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="160"
      y="55"
      width="12"
      height="118"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="320"
      y="115"
      width="12"
      height="58"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="32"
      y="98"
      width="12"
      height="75"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="192"
      y="20"
      width="12"
      height="153"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="352"
      y="76"
      width="12"
      height="97"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="64"
      y="117"
      width="12"
      height="56"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="224"
      y="69"
      width="12"
      height="104"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="384"
      y="31"
      width="12"
      height="142"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="96"
      y="109"
      width="12"
      height="64"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="256"
      y="133"
      width="12"
      height="40"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="416"
      y="20"
      width="12"
      height="153"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="128"
      y="65"
      width="12"
      height="108"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="288"
      y="133"
      width="12"
      height="40"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
    <rect
      x="448"
      width="12"
      height="173"
      rx="6"
      fill="white"
      fillOpacity="0.1"
    />
  </svg>
);

export default DimmedGraph;
